version: "3.9"

services:
  redis:
    image: redis:7
    container_name: npc-redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: npc-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: npc-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data

volumes:
  mongo_data:
  neo4j_data: